### ISSUE TITLE
Failed to execute goal on project simplu3d-tutorial

### ISSUE THREAD

**Issue by magalietecher** [SimPLU3D/simplu3D-tutorial#1]
Bonjour à vous, 

Je tente d'effectuer des simulations en suivant le tutoriel du projet SimPLU et rencontre le problème suivant en réalisant un build non sécurisé avec la formule suivante: mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true. 

[ERROR] Failed to execute goal on project simplu3d-tutorial: Could not resolve dependencies for project fr.ign.cogit:simplu3d-tutorial:jar:1.2-SNAPSHOT: Failed to collect dependencies at fr.ign.cogit:simplu3d:jar:1.2-SNAPSHOT: Failed to read artifact descriptor for fr.ign.cogit:simplu3d:jar:1.2-SNAPSHOT: The following artifacts could not be resolved: fr.ign.cogit:simplu3d:pom:1.2-SNAPSHOT (absent): Could not transfer artifact fr.ign.cogit:simplu3d:pom:1.2-SNAPSHOT from/to ign-snapshots (https://forge-cogit.ign.fr/nexus/content/repositories/snapshots/): Connect to forge-cogit.ign.fr:443 [forge-cogit.ign.fr/192.134.133.40] failed: connect timed out -> [Help 1]

Je rencontre également le même problème sur les autres projets en effectuant des build non sécurisés également.

Étant non familière, je ne trouve pas la source du problème. Pourriez-vous m'aider pour le résoudre? 
Je vous remercie.

**Comment by JusteRaimbault** [comment]
See related issue when building geoxygene: https://github.com/IGNF/geoxygene/issues/43
Apparently @julienperret has fixed simplu3d the same way he did for geoxygene (https://github.com/SimPLU3D/simplu3D/commit/ce9ef6e7ddf8a1b9719f46269768fcc6732f2555 ) so at least building simplu3d should work - trying this now

**Comment by JusteRaimbault** [comment]
I managed to compile `simplu3d-tutorial` after changing `<simplu3d.version>1.2-SNAPSHOT</simplu3d.version>` to 1.3 in `pom.xml` (the fixed version was deployed as 1.3) - could you try this on your side?

**Comment by magalietecher** [comment]
Hi thank you for your help. I have not seen https://github.com/IGNF/geoxygene/issues/43 before posting mine. 
Eventually I tried to: 
• Download the simplu3d and simplu3d-rules pom.xml modified by @julienperret 
• Had a personnal token and all repositories to my m2/settings.xml like this: 

```
<activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>
<profiles>
<profile>
<repositories>
<repository>
	  <id>osgeo</id>
	  <url>https://repo.osgeo.org/repository/release/</url>
          <snapshots><enabled>false</enabled></snapshots>
	  <releases><enabled>true</enabled></releases>
</repository>
<repository>
          <id>geoxygene</id>
          <url>https://maven.pkg.github.com/IGNF/geoxygene</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
</repository>
<repository>
          <id>simplu3D-tutorial</id>
          <url>https://maven.pkg.github.com/simPLU3D/simplu3D-tutorial</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
</repository>
<repository>
          <id>simplu3D</id>
          <url>https://maven.pkg.github.com/simPLU3D/simplu3D</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
</repository>
<repository>
	<id>librjmcmc4j</id>
	<url>https://maven.pkg.github.com/IGNF/librjmcmc4j</url>
        <snapshots>
        <enabled>true</enabled>
          </snapshots>
</repository>
</repositories>
</profile>
</profiles>
<servers>
    <server>
      <id>github</id>
      <username>USERNAME</username>
      <password>PERSONNAL TOKEN</password>
    </server>
  </servers>
</settings>
```

• add the certficate of those repositories to my trustore.jks

But I still have Build failures with these errors: 
For `simplu3D` : 

`[ERROR] Failed to execute goal on project simplu3d: Could not resolve dependencies for project fr.ign.cogit:simplu3d:jar:1.3: Failed to collect dependencies at fr.ign.cogit:simplu3d-rules:jar:1.3: Failed to read artifact descriptor for fr.ign.cogit:simplu3d-rules:jar:1.3: Could not transfer artifact fr.ign.cogit:simplu3d-rules:pom:1.3 from/to geoxygene (https://maven.pkg.github.com/IGNF/geoxygene): Access denied to https://maven.pkg.github.com/IGNF/geoxygene/fr/ign/cogit/simplu3d-rules/1.3/simplu3d-rules-1.3.pom. Error code 401, Unauthorized -> [Help 1]`

and For `simplu3D-rules` : 

`[ERROR] Failed to execute goal on project simplu3d-rules: Could not resolve dependencies for project fr.ign.cogit:simplu3d-rules:jar:1.3: Failed to collect dependencies at fr.ign.cogit:geoxygene-sig3d-gui:jar:1.10-SNAPSHOT: Failed to read artifact descriptor for fr.ign.cogit:geoxygene-sig3d-gui:jar:1.10-SNAPSHOT: The following artifacts could not be resolved: fr.ign.cogit:geoxygene-sig3d-gui:pom:1.10-SNAPSHOT (absent): Could not transfer artifact fr.ign.cogit:geoxygene-sig3d-gui:pom:1.10-SNAPSHOT from/to geoxygene (https://maven.pkg.github.com/IGNF/geoxygene): status code: 401, reason phrase: Unauthorized (401) -> [Help 1]`

• I also modified `simplu3D-tutorial pom.xm`l with 1.3 version instead of 1.2-snapshot with 

```
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<simplu3d.version>1.3</simplu3d.version>
</properties>
```

but i have the same error due to forge-cogit

`[ERROR] Failed to execute goal on project simplu3d-tutorial: Could not resolve dependencies for project fr.ign.cogit:simplu3d-tutorial:jar:1.2-SNAPSHOT: Failed to collect dependencies at fr.ign.cogit:simplu3d:jar:1.3: Failed to read artifact descriptor for fr.ign.cogit:simplu3d:jar:1.3: The following artifacts could not be resolved: fr.ign.cogit:simplu3d:pom:1.3 (absent): Could not transfer artifact fr.ign.cogit:simplu3d:pom:1.3 from/to ign-releases (https://forge-cogit.ign.fr/nexus/content/repositories/releases/): Connect to forge-cogit.ign.fr:443 [forge-cogit.ign.fr/192.134.133.40] failed: connect timed out -> [Help 1]`

Moreover, when i try to go to https://maven.pkg.github.com/IGNF/geoxygene/fr/ign/cogit/simplu3d-rules/1.3 i have this error : 
`maven package "fr.ign.cogit" does not exist under owner "IGNF"`

I do not understand why simplu3D and simplu3D-rules do not work because they are already modified.. 
Thank you in advance

**Comment by julienperret** [comment]
Sorry for the delay.
I updated the pom. Could you try again please?

**Comment by magalietecher** [comment]
Hi, thank you for your answer, 
I download the new code and i still have a build failure with this error: 
`[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building simplu3d 1.3
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://repo.osgeo.org/repository/release/fr/ign/cogit/simplu3d-rules/1.3/simplu3d-rules-1.3.pom
[INFO] Downloading: https://maven.pkg.github.com/IGNF/geoxygene/fr/ign/cogit/simplu3d-rules/1.3/simplu3d-rules-1.3.pom
[INFO] Downloading: https://maven.pkg.github.com/IGNF/librjmcmc4j/fr/ign/cogit/simplu3d-rules/1.3/simplu3d-rules-1.3.pom
[INFO] Downloading: https://maven.pkg.github.com/SimPLU3D/simplu3D-rules/fr/ign/cogit/simplu3d-rules/1.3/simplu3d-rules-1.3.pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/fr/ign/cogit/simplu3d-rules/1.3/simplu3d-rules-1.3.pom
[INFO] Downloading: https://repo.osgeo.org/repository/release/fr/ign/librjmcmc4j-core/1.2/librjmcmc4j-core-1.2.pom
[INFO] Downloading: https://maven.pkg.github.com/IGNF/geoxygene/fr/ign/librjmcmc4j-core/1.2/librjmcmc4j-core-1.2.pom
[INFO] Downloading: https://maven.pkg.github.com/IGNF/librjmcmc4j/fr/ign/librjmcmc4j-core/1.2/librjmcmc4j-core-1.2.pom
[INFO] Downloading: https://maven.pkg.github.com/SimPLU3D/simplu3D-rules/fr/ign/librjmcmc4j-core/1.2/librjmcmc4j-core-1.2.pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/fr/ign/librjmcmc4j-core/1.2/librjmcmc4j-core-1.2.pom
[INFO] Downloading: https://repo.osgeo.org/repository/release/fr/ign/librjmcmc4j-geometry/1.2/librjmcmc4j-geometry-1.2.pom
[INFO] Downloading: https://maven.pkg.github.com/IGNF/geoxygene/fr/ign/librjmcmc4j-geometry/1.2/librjmcmc4j-geometry-1.2.pom
[INFO] Downloading: https://maven.pkg.github.com/IGNF/librjmcmc4j/fr/ign/librjmcmc4j-geometry/1.2/librjmcmc4j-geometry-1.2.pom
[INFO] Downloading: https://maven.pkg.github.com/SimPLU3D/simplu3D-rules/fr/ign/librjmcmc4j-geometry/1.2/librjmcmc4j-geometry-1.2.pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/fr/ign/librjmcmc4j-geometry/1.2/librjmcmc4j-geometry-1.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.344 s
[INFO] Finished at: 2024-02-08T18:15:35+01:00
[INFO] Final Memory: 11M/269M
[INFO] ------------------------------------------------------------------------


[WARNING] The requested profile "github" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project simplu3d: Could not resolve dependencies for project fr.ign.cogit:simplu3d:jar:1.3:
Failed to collect dependencies at fr.ign.cogit:simplu3d-rules:jar:1.3: Failed to read artifact descriptor for fr.ign.cogit:simplu3d
rules:jar:1.3: Could not transfer artifact fr.ign.cogit:simplu3d-rules:pom:1.3 from/to osgeo
(https://repo.osgeo.org/repository/release/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]`

 I have modified my .m2/settings with personalized token access by adding this: 

```
<server>
      <id>github</id>
      <username>magalietecher</username>
      <password>password</password>
    </server>
```

and I have the same problem with simplu3D. 

Thank you for your help. 
Magalie

**Comment by julienperret** [comment]
Maven is very verbose so you might have missed the warning:
`[WARNING] The requested profile "github" could not be activated because it does not exist.`
Could you check your settings file according to:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

**Comment by magalietecher** [comment]
Hi thank you for your help.
I am novice so i hope i understand correctly: 
I modify my settings in ./m2 like this: 

```
<settings>
<activeProfiles>
    <activeProfile>github</activeProfile>
  </activeProfiles>
<profiles>
<profile>
>id>github>/id>
<repositories>
 <repository>
  <id>github</id>
  <url>https://maven.pkg.github.com/ignf/geoxygene</url>
  <snapshots>
   <enabled>true</enabled>
  </snapshots>
 </repository>
<repository>
  <id>github</id>
  <url>https://maven.pkg.github.com/simplu3d/simplu3D</url>
  <snapshots>
   <enabled>true</enabled>
  </snapshots>
</repository>
<repository>
  <id>github</id>
  <url>https://maven.pkg.github.com/ignf/librjmcmc4j</url>
  <snapshots>
   <enabled>true</enabled>
  </snapshots>
</repository>
<repository>
  <id>github</id>
  <url>https://maven.pkg.github.com/simplu3d/simplu3D-tutorial</url>
  <snapshots>
   <enabled>true</enabled>
  </snapshots>
 </repository>
</repositories>
</profile>
</profiles>
<servers>
    <server>
      <id>github</id>
      <username>magalietecher</username>
      <password>personnal token</password>
    </server>
  </servers>
</settings>
```

And still get the same error of profile which does not exist so i try to add details profile activation in the simplu-3d tutorial pom.xml (https://maven.apache.org/guides/introduction/introduction-to-profiles.html) like this: 

```
<profiles>
    <profile>
    <id>github</id>
    <activation>
    <activeByDefault>true</activeByDefault>
    </activation>
    </profile>
</profiles>
```

I still have a build failure but with **another error** which i do not find a solution already.. 

`Failed to execute goal on project simplu3d-tutorial: Could not resolve dependencies for project fr.ign.cogit:simplu3d-tutorial:jar:1.2-SNAPSHOT: Failed to collect dependencies at fr.ign.cogit:simplu3d:jar:1.3: Failed to read artifact descriptor for fr.ign.cogit:simplu3d:jar:1.3: Could not transfer artifact fr.ign.cogit:simplu3d:pom:1.3 from/to geoxygene (https://maven.pkg.github.com/IGNF/geoxygene): Access denied to https://maven.pkg.github.com/IGNF/geoxygene/fr/ign/cogit/simplu3d/1.3/simplu3d-1.3.pom. Error code 401, Unauthorized `

Thank you
Magalie

**Comment by julienperret** [comment]
There is a typo in your settings file:
`>id>github>/id>`
should be
`<id>github>/id>`

Otherwise, please check that your token has the following right:
read:packages
